apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoenix-pvc
  labels:
    app: phoenix
    component: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
