# T081: Orchestrator service account
{{- if .Values.orchestrator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mastragen.serviceAccountName" . }}
  labels:
    {{- include "mastragen.orchestrator.labels" . | nindent 4 }}
  {{- with .Values.orchestrator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
